FROM python:3.13-slim

RUN apt-get update && apt-get install -y pip
RUN pip install --upgrade pip

WORKDIR /app

COPY requirements.txt .
ADD . /app

RUN pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]